<?php

define('LANG_DEFAULT_THEME_BG', 'Tło strony');
define('LANG_DEFAULT_THEME_BG_IMAGE', 'Zdjęcie w tle');
define('LANG_DEFAULT_THEME_BG_IMAGE_HINT', 'Wszystkie inne ustawienia zaczną obowiązywać po przesłaniu obrazu');
define('LANG_DEFAULT_THEME_BG_COLOR', 'Kolor tła');
define('LANG_DEFAULT_THEME_BG_REPEAT', 'Powtórz obraz tła');
define('LANG_DEFAULT_THEME_BG_REPEAT_X', 'Powtórz poziomo');
define('LANG_DEFAULT_THEME_BG_REPEAT_Y', 'Powtórz w pionie');
define('LANG_DEFAULT_THEME_BG_REPEAT_NO', 'Bez powtórzeń');
define('LANG_DEFAULT_THEME_BG_REPEAT_XY', 'Powtarzać');
define('LANG_DEFAULT_THEME_BG_POS', 'Pozycja obrazu tła');
define('LANG_DEFAULT_THEME_BG_POS_X', 'Poziomy');
define('LANG_DEFAULT_THEME_BG_POS_X_LEFT', 'Lewy');
define('LANG_DEFAULT_THEME_BG_POS_X_CENTER', 'Centrum');
define('LANG_DEFAULT_THEME_BG_POS_X_RIGHT', 'Prawidłowy');
define('LANG_DEFAULT_THEME_BG_POS_Y', 'Pionowy');
define('LANG_DEFAULT_THEME_BG_POS_Y_TOP', 'Szczyt');
define('LANG_DEFAULT_THEME_BG_POS_Y_CENTER', 'Centrum');
define('LANG_DEFAULT_THEME_BG_POS_Y_BOTTOM', 'Spód');
define('LANG_DEFAULT_THEME_TOP_MARGIN', 'Górny margines strony');
define('LANG_DEFAULT_THEME_LAYOUT', 'Układ strony');
define('LANG_DEFAULT_THEME_LAYOUT_LEFT', 'Lewy');
define('LANG_DEFAULT_THEME_LAYOUT_RIGHT', 'Prawidłowy');
define('LANG_DEFAULT_THEME_LAYOUT_COLUMNS', 'Kolumny');
define('LANG_DEFAULT_THEME_LAYOUT_SIDEBAR_POS', 'Pozycja paska bocznego');
define('LANG_DEFAULT_THEME_COPYRIGHT', 'Prawo autorskie');
define('LANG_DEFAULT_THEME_COPYRIGHT_URL', 'URL praw autorskich');
define('LANG_DEFAULT_THEME_COPYRIGHT_URL_HINT', 'Strona główna domyślnie');
define('LANG_DEFAULT_THEME_COPYRIGHT_YEAR', 'Rok praw autorskich');
define('LANG_DEFAULT_THEME_COPYRIGHT_YEAR_HINT', 'Bieżący rok domyślnie');
define('LANG_DEFAULT_THEME_DISABLE_HELP_ANIM', 'Wyłącz animację przycisku „Pomoc”.');
define('LANG_DEFAULT_THEME_LAYOUT_MAIN', 'Podstawowy układ');
