<?php

define('LANG_MODERN_THEME_GAMMA', 'Gama kolorów');
define('LANG_MODERN_THEME_COLORS', 'Zabarwienie');
define('LANG_MODERN_THEME_BGCOLOR', 'Kolor tła witryny');
define('LANG_MODERN_THEME_HBCOLOR', 'Kolor tła nagłówka witryny');
define('LANG_MODERN_THEME_FBCOLOR', 'Kolor tła stopki witryny');
define('LANG_MODERN_THEME_HCOLOR', 'Kolor tekstu nagłówka witryny');
define('LANG_MODERN_THEME_FCOLOR', 'Kolor tekstu stopki witryny');
define('LANG_MODERN_THEME_BCOLOR', 'Kolor czcionki witryny');
define('LANG_MODERN_THEME_LINK_COLOR', 'Kolor łącza do witryny');
define('LANG_MODERN_THEME_GCOLOR', 'Wybierz kolor z gamy');
define('LANG_MODERN_THEME_SET_MY_COLOR', 'Ustaw własne');
define('LANG_MODERN_THEME_COPYRIGHT', 'Prawo autorskie');
define('LANG_MODERN_THEME_COPYRIGHT_URL', 'Link do praw autorskich');
define('LANG_MODERN_THEME_COPYRIGHT_URL_HINT', 'Jeśli nie jest określony, prowadzi do strony głównej');
define('LANG_MODERN_THEME_COPYRIGHT_YEAR', 'Rok praw autorskich');
define('LANG_MODERN_THEME_COPYRIGHT_YEAR_HINT', 'Jeśli nie określono, wyświetla bieżący');
define('LANG_MODERN_THEME_ENABLE_ROUNDED', 'Włącz zaokrąglanie narożników');
define('LANG_MODERN_THEME_ENABLE_TOPBTN', 'Pokaż górny przycisk');
define('LANG_MODERN_THEME_SHOW_COOKIEALERT', 'Pokaż zgodę z Cookiem');
define('LANG_MODERN_THEME_COOKIEALERT_TEXT', 'Umowa tekstowa dotycząca plików cookie');
define('LANG_MODERN_THEME_COOKIEALERT_AGREE', 'zgadzam się');
define('LANG_MODERN_THEME_ROUNDED_BASE', 'Domyślny promień');
define('LANG_MODERN_THEME_ROUNDED_BASE_LG', 'Duży promień');
define('LANG_MODERN_THEME_ROUNDED_BASE_SM', 'Mały promień');
define('LANG_MODERN_THEME_ENABLE_SHADOWS', 'Włącz cienie');
define('LANG_MODERN_THEME_ENABLE_GRADIENTS', 'Uwzględnij gradienty');
define('LANG_MODERN_THEME_ENABLE_RFS', 'Włącz responsywne rozmiary czcionek');
define('LANG_MODERN_THEME_BASE_FS', 'Podstawowy rozmiar czcionki');
define('LANG_MODERN_THEME_BASE_SPACER', 'Odstępnik');
define('LANG_MODERN_THEME_AVATAR_INLIST_SIZE', 'Rozmiar litery awatara na liście');
define('LANG_MODERN_THEME_AVATAR_INLIST_SIZE_HINT', 'Musi pasować do wstępnie ustawionego rozmiaru awatara listy użytkowników');
define('LANG_MODERN_THEME_PAGINATION_TPL', 'Szablon bloku numeracji stron');
define('LANG_MODERN_THEME_ENABLE_MODAL_BLUR', 'Rozmycie tła przy otwieraniu okien modalnych');
define('LANG_MODERN_THEME_GRID_GUTTER_W', 'Przesunięcie siatki bazowej');
define('LANG_MODERN_C_WHITE', 'Biały');
define('LANG_MODERN_C_GRAY100', 'szary 100');
define('LANG_MODERN_C_GRAY200', 'Szary 200');
define('LANG_MODERN_C_GRAY300', 'szary 300');
define('LANG_MODERN_C_GRAY400', 'Szary 400');
define('LANG_MODERN_C_GRAY500', 'szary 500');
define('LANG_MODERN_C_GRAY600', 'Szary 600');
define('LANG_MODERN_C_GRAY700', 'Szary 700');
define('LANG_MODERN_C_GRAY800', 'Szary 800');
define('LANG_MODERN_C_GRAY900', 'Szary 900');
define('LANG_MODERN_C_BLACK', 'Czarny');
define('LANG_MODERN_C_BLUE', 'Niebieski');
define('LANG_MODERN_C_INDIGO', 'Indygo');
define('LANG_MODERN_C_PURPLE', 'Magenta');
define('LANG_MODERN_C_PINK', 'Różowy');
define('LANG_MODERN_C_RED', 'Czerwony');
define('LANG_MODERN_C_ORANGE', 'Pomarańczowy');
define('LANG_MODERN_C_YELLOW', 'Żółty');
define('LANG_MODERN_C_GREEN', 'Zielony');
define('LANG_MODERN_C_TEAL', 'Turkusowy (niebiesko-zielony)');
define('LANG_MODERN_C_CYAN', 'cyjan (aqua)');
define('LANG_MODERN_C_PRIMARY', 'Kolor podstawowy');
define('LANG_MODERN_C_SECONDARY', 'Kolor drugorzędny');
define('LANG_MODERN_C_SUCCESS', 'Pozytywny kolor');
define('LANG_MODERN_C_INFO', 'Kolor informacji');
define('LANG_MODERN_C_WARNING', 'Kolor ostrzegawczy');
define('LANG_MODERN_C_DANGER', 'Niebezpieczny kolor');
define('LANG_MODERN_C_LIGHT', 'Jasny kolor');
define('LANG_MODERN_C_DARK', 'Ciemny kolor');
define('LANG_MODERN_WIDGETS_SQUARE', 'Przezroczysty №2');
define('LANG_MODERN_WIDGETS_TRANSPARENT', 'Przezroczysty №1');
define('LANG_MODERN_WIDGETS_COMPACT', 'Kompaktowy');
define('LANG_MODERN_LOGO', 'Prześlij swoje podstawowe logo');
define('LANG_MODERN_RASTR_HINT', 'W mapie bitowej');
define('LANG_MODERN_LOGO_SVG', 'Lub wklej podstawowe logo SVG');
define('LANG_MODERN_LOGO_SMALL', 'Prześlij małe logo');
define('LANG_MODERN_LOGO_SMALL_HINT', 'Będzie wyświetlany w niskich rozdzielczościach.');
define('LANG_MODERN_LOGO_SMALL_SVG', 'Lub wstaw małe logo w formacie SVG');
define('LANG_MODERN_VARS', 'Bootstrap4 nadpisane zmienne');
define('LANG_MODERN_VARS_SELECT', 'Wybierz zmienną');
define('LANG_MODERN_FONT_TYPE', 'Czcionka witryny');
define('LANG_MODERN_FONT_TYPE_STR', 'Określ ciąg czcionki ręcznie');
define('LANG_MODERN_FONT_STRING', 'Określ listę priorytetów jednej lub więcej nazw rodzin czcionek c gładkie wykończenie');
define('LANG_MODERN_FONT_GOOGLE', 'Czcionka Google');
define('LANG_MODERN_FAVICON', 'Favicon');
define('LANG_MODERN_FAVICON_FILE', 'Pliki ulubionych');
define('LANG_MODERN_FAVICON_HEAD', 'Lub podaj gotowy kod HTML dodany do &lt;head&gt; znacznik strony');
define('LANG_MODERN_JS_PRINT_HEAD', 'Drukuj JavaScript w nagłówku strony');
