<?php

    define('LANG_LOADING',                   'Ładowanie...');
    define('LANG_SENDING',                   'Wysyłanie danych...');
    define('LANG_MORE',                      'Więcej');
    define('LANG_VERSION',                   'Wersja');

    //CONTENT
    define('LANG_CONTENT_TYPE',              'Typ zawartości');
    define('LANG_CONTENT_TYPE_SETTINGS',     'Skonfiguruj %s');
    define('LANG_CONTENT_SELECT_ITEM',       'Wybierz %s');
    define('LANG_CONTENT_ADD_ITEM',          'Dodaj %s');
    define('LANG_CONTENT_BIND_ITEM',         'Powiąż %s');
    define('LANG_CONTENT_BIND_ITEMS',        'Wiązać');
    define('LANG_CONTENT_UNBIND_ITEM',       'Rozwiąż %s');
    define('LANG_CONTENT_UNBIND_ITEMS',      'Rozwiązać');
    define('LANG_CONTENT_EDIT_ITEM',         'Edytuj %s');
    define('LANG_CONTENT_DELETE_ITEM',       'Usuń %s');
    define('LANG_CONTENT_DELETE_ITEM_CONFIRM',  'Czy na pewno chcesz usunąć %s?');
    define('LANG_CONTENT_RETURN_CONFIRM',    'Czy na pewno chcesz pobrać ten element z moderacji?\nZostanie on przeniesiony do wersji roboczych.');
    define('LANG_CONTENT_SAVE_DRAFT',		 'Zapisz w wersji roboczej');
    define('LANG_CONTENT_MOVE_DRAFT',		 'Przejdź do wersji roboczych');
    define('LANG_CONTENT_DRAFT_NOTICE',		 'Element jest ukryty w wersjach roboczych');
    define('LANG_CONTENT_DRAFT_LIST',		 'Warcaby');
    define('LANG_CONTENT_NOT_APPROVED',      'Oczekuje na zatwierdzenie');
    define('LANG_CONTENT_EDITED',            'Edytowane');
    define('LANG_CONTENT_NOT_IS_PUB',		 'Nie publikowany');
    define('LANG_CONTENT_OWN_ITEMS',		 'Tylko mój');
    define('LANG_CONTENT_BIND_ITEM_FIND_HINT','Wpisz część wartości pola');

    define('LANG_SHOW_FILTER',               'Pokaż filtr');
    define('LANG_FILTER',                    'Filtr');
    define('LANG_FILTERS',                   'Filtry');
    define('LANG_FILTER_FIELD',              'Filtruj według pola');
    define('LANG_FILTER_ADD',                'Nowy filtr');
    define('LANG_FILTER_LIKE',               'zawiera');
    define('LANG_FILTER_NOT_LIKE',           'nie zawiera');
    define('LANG_FILTER_LIKE_BEGIN',         'zaczynać z');
    define('LANG_FILTER_LIKE_END',           'kończy się na');
    define('LANG_FILTER_DATE_YOUNGER',       'nie wcześniej, dni');
    define('LANG_FILTER_DATE_OLDER',         'nie później, dni');
    define('LANG_FILTER_NOT_NULL',           'wypełniony');
    define('LANG_FILTER_IS_NULL',            'nie wypełnione');
    define('LANG_FILTER_APPLY',              'Stosować');
    define('LANG_FILTER_Adres URL',                'Adres URL');
    define('LANG_FILTER_SAVE_DIFF_ORDER',    'Zapisz inną kolejność');
    define('LANG_SORTING_FIELD',             'Sortuj według pola');
    define('LANG_SORTING',                   'Sortować');
    define('LANG_SORTING_ADD',               'Nowa zasada');
    define('LANG_SORTING_ASC',               'rosnąco');
    define('LANG_SORTING_DESC',              'malejąco');
    define('LANG_SORTING_BYORDER',           'Na zamówienie');
    define('LANG_SORTING_BYTIME',            'Według czasu wykonania');
    define('LANG_SORTING_BYDATE',            'Według daty');
    define('LANG_SORTING_BYREL',             'Według trafności');
    define('LANG_PHOTO',                     'Obraz');
    define('LANG_PHOTOS',                    'Obrazy');
    define('LANG_COMMENTS',                  'Uwagi');
    define('LANG_RATING',                    'Ocena');
    define('LANG_KARMA',                     'Reputacja');
    define('LANG_KARMA_UP',                  'Głosować');
    define('LANG_KARMA_DOWN',                'Przegłosować');
    define('LANG_CSS_CLASS',                 'klasa CSS');
    define('LANG_CSS_CLASS_WRAP',            'Klasa CSS kontenera');
    define('LANG_CSS_CLASS_TITLE',           'Tytułowa klasa CSS');
    define('LANG_CSS_CLASS_BODY',            'Klasa CSS ciała');
    define('LANG_GROUP',                     'Grupa');
    define('LANG_GROUPS',                    'Grupy');
    defWe('LANG_WROTE_IN_GROUP',            'W');
    define('LANG_DESIGN',					 'Projekt');
    define('LANG_TABLE',					 'Tabela');

    //WIDGETS
    define('LANG_WP_SYSTEM',                 'System');
    define('LANG_WP_CUSTOM',                 'Zwyczaj');
    define('LANG_WP_ALL_PAGES',              'Wszystkie strony');
    define('LANG_WP_HOME_PAGE',              'Strona główna');
    define('LANG_WIDGET_TAB_PREV',           'Grupuj z poprzednim widżetem');
    define('LANG_WIDGET_TITLE_LINKS',        'Linki w nagłówku widżetu');
    define('LANG_WIDGET_TITLE_LINKS_HINT',   'W <b><em>Tytuł | Format adresu URL</em></b>, na przykład <b><em>Google | http://www.google.com</em></b><br>Jeśli link jest ujęty w nawias klamrowy <b>{ }</b>, będzie widoczny tylko dla autoryzowanych użytkowników<br>Jeden łącze w linii');
    define('LANG_WIDGET_WRAPPER_TPL',		 'Szablon kontenera');
    define('LANG_WIDGET_WRAPPER_TPL_NO',     'Bez szablonu kontenera');
    define('LANG_WIDGET_BODY',	             'Ciało widżetu');
    define('LANG_WIDGET_WRAPPER_TPL_CUST',	 'Niestandardowy kontener HTML');
    define('LANG_WIDGET_WRAPPER_TPL_HINT',	 'Plik z katalogu <b>widgets</b> Twojego szablonu');
    define('LANG_WIDGET_BODY_TPL',			 'Szablon widżetu');
    define('LANG_WIDGET_BODY_TPL_HINT',	     'Plik z katalogu <b>%s</b> Twojego szablonu');
    define('LANG_WIDGET_DEVICE',			 'Które urządzenia wyświetlają widżet');
    define('LANG_WIDGET_LANG_SELECT',		 'Dla jakich języków będzie wyświetlany widżet?');
    define('LANG_WIDGET_TEMPLATE_LAYOUT',	 'Wyświetlaj na układach');
    define('LANG_DESKTOP_DEVICES',  'Komputery stacjonarne');
    define('LANG_TABLET_DEVICES',  'Tabletki');
    define('LANG_MOBILE_DEVICES',  'Telefony');

    //PARSERS
    define('LANG_PARSER_PREFIX',             'Prefiks');
    define('LANG_PARSER_LIST_WHERE', 'Skąd utworzyć listę');
    define('LANG_PARSER_LIST_WHERE_PRE', 'Od wartości zadanych');
    define('LANG_PARSER_LIST_WHERE_TBL', 'Tabela bazy danych (bez prefiksu)');
    define('LANG_PARSER_LIST_COND', 'Warunki wyboru');
    define('LANG_PARSER_LIST_COND_HINT', 'W formacie JSON, na przykład [{"field": "foo", "condition": "eq", "value": "bar"}].');
    define('LANG_PARSER_LIST_WHERE_ID', 'Pole z identyfikatorem rekordu');
    define('LANG_PARSER_LIST_WHERE_TITLE', 'Nazwa rekordu');
    define('LANG_PARSER_LIST_SORT_BY_KEYS',  'Kluczami');
    define('LANG_PARSER_LIST_SORT_BY_VALUES','Według wartości');
    define('LANG_PARSER_LIST_ORDER', 'Format to pole:kierunek, na przykład tytuł:asc');
    define('LANG_PARSER_LIST_IS_AUTOLINK',     'Automatyczne łączenie');
    define('LANG_PARSER_LIST_ADD_EMPTY',     'Dodaj pustą wartość na początku wartości zadanych');
    define('LANG_PARSER_LIST_IS_AUTOLINK_HINT', 'Włączenie tej opcji powoduje podział (przecinkiem) wartości pola na osobne słowa, z których każde tworzy odwołanie.');
    define('LANG_PARSER_LIST_IS_AUTOLINK_FILTER', 'Opcja „Pokaż w filtrze” powinna być włączona.');
    define('LANG_PARSER_BITMASK_CHECKBOX_MULTIPLE', 'Wielokrotny wybór za pomocą pól wyboru');
    define('LANG_PARSER_BITMASK_LIST_CLASS', 'Lista klas css');
    define('LANG_PARSER_BITMASK_MAX',        'Lista pozycji maksymalna liczba');
    define('LANG_PARSER_BITMASK_MAX_HINT',   'w zadanych wartościach');
    define('LANG_PARSER_CAPTION',            'Podpis');
    define('LANG_PARSER_STRING',             'Strunowy');
    define('LANG_PARSER_STRING_DISPLAY_VARIANT','Jak wyświetlić w filtrze');
    define('LANG_PARSER_STRING_ENTER_DEFAULT',  'Wprowadź wartości domyślne z istniejących danych');
    define('LANG_PARSER_STRING_SELECT',      'Wybierz z wartościami domyślnymi');
    define('LANG_PARSER_STRING_CHECKBOX',    'Pole wyboru nie jest pustym polem');
    define('LANG_PARSER_HIDDEN',             'Ukryte pole');
    define('LANG_PARSER_NUMBER',             'Numer');
    define('LANG_PARSER_NUMBER_FILTER_RANGE','Filtruj według zakresu');
    define('LANG_PARSER_NUMBER_FILTER_RANGE_SLIDE','Zakres jako suwak');
    define('LANG_PARSER_NUMBER_FILTER_STEP', 'Krok suwaka');
    define('LANG_PARSER_NUMBER_FILTER_RANGE_SI', 'Pokaż pola wprowadzania za pomocą suwaka');
    define('LANG_PARSER_NUMBER_UNITS',       'Jednostki');
    define('LANG_PARSER_NUMBER_DECIMAL_INT', 'Liczba cyfr całej części');
    define('LANG_PARSER_NUMBER_DECIMAL_S',   'Liczba cyfr po przecinku');
    define('LANG_PARSER_NUMBER_TRIM_ZERO',   'Przytnij dziesiętne zero');
    define('LANG_PARSER_NUMBER_DEC_POINT',   'Kropka dziesiętna');
    define('LANG_PARSER_NUMBER_IS_CEIL',     'Tylko numery sufitów');
    define('LANG_PARSER_NUMBER_THOUSANDS_SEP', 'separator tysięcy');
    define('LANG_PARSER_NUMBER_UNITS_SEP',   'Przekładka jednostek');
    define('LANG_PARSER_NUMBER_IS_ABS',      'Tylko liczby dodatnie');
    define('LANG_PARSER_NUMBER_SAVE_ZERO',   'Zapisz wartość zerową');
    define('LANG_PARSER_CITY',               'Lokalizacja');
    define('LANG_PARSER_CITY_LOCATION_TYPE', 'Typ Lokacji');
    define('LANG_PARSER_CITY_AUTO_DETECT',   'Automatycznie identyfikuj kraj');
    define('LANG_PARSER_CITY_LOCATION_GROUP', 'Nazwa dla grupy');
    define('LANG_PARSER_CITY_LOCATION_GROUP_HINT', 'Jeśli chcesz połączyć lokalizacje kraj-region-miasto, wprowadź nazwę dla ujednolicenia wszystkich pól. Jako minimum należy ustalić pola takie jak „Kraj” i „Region”');
    define('LANG_PARSER_CITY_OUTPUT_STRING', 'Ciąg wyjściowy wartości pola');
    define('LANG_PARSER_CITY_OUTPUT_STRING_HINT', 'Na przykład „{kraj}, {miasto}”, gdzie nazwy pól kraju i miasta. Warto użyć, wyłączając wyjście dla pozostałych grup pól, pokazując pożądane wartości w tym polu. Jeśli nie określono - wartość wyjściowa bieżącego pola.');
    define('LANG_PARSER_CHECKBOX',           'Pole wyboru');
    define('LANG_PARSER_TEXT',               'pole tekstowe');
    define('LANG_PARSER_TEXT_MAX_LEN',       'Maksymalna długość');
    define('LANG_PARSER_TEXT_MIN_LEN',       'Minimalna długość');
    define('LANG_PARSER_SHOW_SYMBOL_COUNT',  'Pokaż liczbę znaków');
    define('LANG_PARSER_USE_INPUTMASK',      'Użyj maski wprowadzania');
    define('LANG_PARSER_INPUTMASK',          'Maska wprowadzania');
    define('LANG_PARSER_INPUTMASK_HINT',     '9 - numeryczny, a - alfabetyczny, * - alfanumeryczny. Przeczytaj więcej w <a target="_blank" href="https://docs.instantcms.ru/manual/ctypes/fields/types#строковое-поле">dokumentacji</a>');
    define('LANG_PARSER_IS_STRIP_TAGS',      'Usuń wszystkie znaczniki HTML podczas zapisywania');
    define('LANG_PARSER_HTML',               'Tekst HTML');
    define('LANG_PARSER_HTML_EDITOR',        'Edytor WYSIWYG');
    define('LANG_PARSER_HTML_EDITOR_GR',     'Edytory WYSIWYG dla grup');
    define('LANG_PARSER_HTML_FILTERING',     'Zdezynfekuj wejście');
    define('LANG_PARSER_PARSE_PATTERNS',     'Przetwarzaj specjalne szablony');
    define('LANG_PARSER_PARSE_PATTERNS_HINT', 'Użyj pól wejściowych, wstawiając ich nazwy w nawiasach klamrowych. Na przykład dla typów treści: <strong>{title}</strong>, <strong>{category}</strong> itp. Możesz użyć przetwarzania wartości, więcej w <a target="_blank" href=" https://docs.instantcms.ru/en/manual/settings/seo-patterns">dokumentacja</a>');
    define('LANG_PARSER_BUILD_REDIRECT_LINK', 'Linki zewnętrzne przez przekierowanie, jeśli oczyszczone dane wejściowe');
    define('LANG_PARSER_HTML_TEASER_LEN',    'Skróć długość tekstu w widoku listy');
    define('LANG_PARSER_HTML_TEASER_LEN_HINT','Tekst zostanie obcięty do określonej długości, formatowanie zostanie usunięte');
    define('LANG_PARSER_HTML_TEASER_POSTFIX', 'Dodaj tekst do otrzymanej linii');
    define('LANG_PARSER_HTML_TEASER_TYPE',    'Rodzaj wykończenia');
    define('LANG_PARSER_HTML_TEASER_TYPE_NULL','Cięcie w dowolnym miejscu');
    define('LANG_PARSER_HTML_TEASER_TYPE_S', 'Ostatnie zdanie');
    define('LANG_PARSER_HTML_TEASER_TYPE_W', 'Najnowsze słowo');
    define('LANG_PARSER_SHOW_SHOW_MORE',     'Pokaż przycisk „Więcej”.');
    define('LANG_PARSER_BBCODE',             'Pole tekstowe z kodem BB');
    define('LANG_PARSER_LIST',               'Lista');
    define('LANG_PARSER_LIST_FILTER_HINT',   'Indeks pozycji');
    define('LANG_PARSER_LIST_FILTER_MULTI',  'Zezwalaj na wielokrotny wybór w filtrze');
    define('LANG_PARSER_LIST_FILTER_MULTICH',  'Wiele pól wyboru');
    define('LANG_PARSER_LIST_AS_RADIO_BTN',  'Wyświetl listę jako przyciski opcji');
    define('LANG_PARSER_LIST_GROUPS',        'Lista grup użytkowników');
    define('LANG_PARSER_LIST_GROUPS_SHOW_GUESTS',     'Pokaż element „Goście”.');
    define('LANG_PARSER_LIST_IS_MULTIPLE',   'Zezwalaj na wielokrotny wybór');
    define('LANG_PARSER_LIST_MULTIPLE',      'Lista wielu');
    define('LANG_PARSER_LIST_MULTIPLE_SHOW_ALL',      'Pokaż pozycję „Wszystkie”.');
    define('LANG_PARSER_URL',                'Połączyć');
    define('LANG_PARSER_URL_REDIRECT',       'Linki przez przekierowanie');
    define('LANG_PARSER_URL_AUTO_HTTP',      'Dodaj http:// automatycznie');
    define('LANG_PARSER_URL_NOFOLLOW',       'Dodaj atrybut rel="nofollow".');
    define('LANG_PARSER_URL_CSS_CLASS',      'Połącz klasę CSS');
    define('LANG_PARSER_URL_TITLE',          'Ustaw opcję tytułu linku');
    define('LANG_PARSER_URL_TITLE_HINT',     'Aby wyświetlić tytuł linku, wprowadź jego nazwę za pomocą znaku „|”, na przykład: http://google.com|Google');
    define('LANG_PARSER_AGE',                'Wiek');
    define('LANG_PARSER_AGE_DATE_TITLE',     'Tytuł daty rozpoczęcia');
    define('LANG_PARSER_AGE_FILTER_RANGE',   'Filtruj według zakresu');
    define('LANG_PARSER_AGE_FROM_DATE',      'Odliczaj od podanej daty');
    define('LANG_PARSER_AGE_FROM_DATE_HINT', 'Jeśli nie zostanie określony, liczenie zostanie przeprowadzone od bieżącego czasu');
    define('LANG_PARSER_DATE',               'Data');
    define('LANG_PARSER_DATE_FILTER_HINT',   'RRRR-MM-DD');
    define('LANG_PARSER_DATE_SHOW_DATE',     'Pokaż datę');
    define('LANG_PARSER_DATE_SHOW_TIME',     'Czas na przedstawienie');
    define('LANG_PARSER_USER',               'Użytkownik');
    define('LANG_PARSER_USER_FILTER_HINT',   'Identyfikator użytkownika');
    define('LANG_PARSER_USERS',              'Lista użytkowników');
    define('LANG_PARSER_PARENT',             'Rodzic');
    define('LANG_PARSER_PARENT_STYLE',       'W stylu przedmiotu');
    define('LANG_PARSER_PARENT_STYLE1',      'Lista typów zawartości');
    define('LANG_PARSER_PARENT_STYLE2',      'Prosta lista linków');
    define('LANG_PARSER_IMAGE',              'Obraz');
    define('LANG_PARSER_IMAGE_SPELL',        'obraz|obraz|obrazy');
    define('LANG_PARSER_IMAGE_DELETE',       'Usunąć obraz z serwera?');
    define('LANG_PARSER_IMAGES',             'Wiele obrazów');
    define('LANG_PARSER_IMAGE_DEFAULT',      'Obraz domyślny');
    define('LANG_PARSER_IMAGE_ALLOW_IMPORT_LINK', 'Zezwalaj na import z łącza');
    define('LANG_PARSER_FIRST_IMAGE_EMPHASIZE', 'Podkreśl pierwszy obraz we wpisie');
    define('LANG_PARSER_IMAGE_MAX_COUNT',    'Maksymalna liczba obrazów');
    define('LANG_PARSER_IMAGE_MAX_COUNT_HINT', 'Maksymalnie %s');
    define('LANG_PARSER_SMALL_IMAGE_PRESET', 'Ustawienie miniatur');
    define('LANG_PARSER_IMAGE_SIZE_UPLOAD',  'Twórz miniatury');
    define('LANG_PARSER_IMAGE_SIZE_TEASER',  'Rozmiar obrazu na liście');
    define('LANG_PARSER_IMAGE_SIZE_FULL',    'Rozmiar obrazu we wpisie');
    define('LANG_PARSER_IMAGE_SIZE_MODAL',   'Rozmiar obrazu we wpisie z modalem');
    define('LANG_PARSER_IMAGE_SIZE_MICRO',   'Mikro');
    define('LANG_PARSER_IMAGE_SIZE_SMALL',   'Mały');
    define('LANG_PARSER_IMAGE_SIZE_NORMAL',  'Średni');
    define('LANG_PARSER_IMAGE_SIZE_BIG',     'Duży');
    define('LANG_PARSER_IMAGE_SIZE_ORIGINAL','Oryginalny');
    define('LANG_PARSER_IMAGE_TO_ITEM_LINK', 'Link do wpisu podczas przeglądania listy');
    define('LANG_PARSER_COLOR',              'Narzędzie do wybierania kolorów');
    define('LANG_PARSER_COLOR_CT',           'Typ bloku wyboru koloru');
    define('LANG_PARSER_COLOR_OPACITY',      'Włącz przezroczystość kolorów');
    define('LANG_PARSER_COLOR_CT_HUE',       'Odcień');
    define('LANG_PARSER_COLOR_CT_SATURATION', 'Nasycenie');
    define('LANG_PARSER_COLOR_CT_BRIGHTNESS', 'Jasność');
    define('LANG_PARSER_COLOR_CT_WHEEL',     'Koło');
    define('LANG_PARSER_COLOR_CT_SWATCHES',  'Tylko wstępnie ustawione wartości');
    define('LANG_PARSER_COLOR_CT_SWATCHES_OPT', 'Wstępnie ustawione wartości');
    define('LANG_PARSER_FILE',               'Plik');
    define('LANG_PARSER_FILE_LABEL',         'Etykieta łącza do pliku');
    define('LANG_PARSER_FILE_LABEL_NAME',    'Nazwa pliku');
    define('LANG_PARSER_FILE_LABEL_GET',     'Pobierać');
    define('LANG_PARSER_FILE_LABEL_COUNTER', 'pobrane');
    define('LANG_PARSER_FILE_EXTS',          'Dozwolone rozszerzenia plików');
    define('LANG_PARSER_FILE_EXTS_HINT',     'Lista rozszerzeń oddzielona przecinkami');
    define('LANG_PARSER_FILE_EXTS_FIELD_HINT',     'Dozwolone typy plików: %s');
    define('LANG_PARSER_FILE_SIZE_FIELD_HINT',     'Maksymalny rozmiar pliku: %s');
    define('LANG_PARSER_FILE_MAX_SIZE',      'Maksymalny rozmiar pliku, Mb');
    define('LANG_PARSER_FILE_MAX_SIZE_PHP',  'Nie więcej niż %d Mb (dozwolone w ustawieniach PHP)');
    define('LANG_PARSER_FILE_SHOW_SIZE',     'Pokaż rozmiar pliku');
    define('LANG_PARSER_FILE_SHOW_COUNTER',  'Pokaż liczbę pobrań');
    define('LANG_PARSER_CURRENT_TIME',       'Obecny czas');
    define('LANG_PARSER_IN_FULLTEXT_SEARCH', 'Uwzględnij w indeksie pełnotekstowym');
    define('LANG_PARSER_IN_FULLTEXT_SEARCH_HINT', 'Uwaga! Indeks zostanie odbudowany po zmianie opcji. W przypadku dużych stołów może to zająć dużo czasu.');
    define('LANG_PARSER_ADD_FROM_LINK', 'dodać za pomocą linku');
    define('LANG_PARSER_ENTER_IMAGE_LINK', 'Wprowadź link do obrazu');
    define('LANG_OR', 'Lub');
    define('LANG_BEGIN_TYPING', 'Zacznij pisać lub wybierz z listy');
    define('LANG_PARSER_FORMS',              'Formularze');
    define('LANG_PARSER_TOOLBAR',            'pasek narzędzi');
    define('LANG_PARSER_TOOLBAR_FL_TITLE',   'Pola wyjściowe');
    define('LANG_PARSER_TOOLBAR_FL_HINT',    'Ikonę można określić za pomocą dwukropka, na przykład solid:user, gdzie solid to nazwa pliku svg sprite'a w szablonach/template/images/icons. Jeśli podasz coś innego przez drugi dwukropek, będzie to nazwa klasy CSS kontenera, na przykład solid:user:btn.');
    define('LANG_PARSER_TOOLBAR_FL_SEL',     'Wybierz pole i w razie potrzeby określ ikonę');

    //USERS
    define('LANG_USER',                      'Użytkownik');
    define('LANG_USERS',                     'Użytkownicy');
    define('LANG_AUTHOR',                    'Autor');
    define('LANG_REGISTRATION',              'Rejestracja');
    define('LANG_USER_REGISTRATION',         'Rejestracja Użytkownika');
    define('LANG_CREATE_ACCOUNT',            'Zarejestruj się, proszę.');
    define('LANG_LOG_IN',                    'Zaloguj sie');
    define('LANG_LOG_IN_ACCOUNT',            'Zaloguj się przy użyciu swojego konta');
    define('LANG_LOG_IN_OPENID',             'Zaloguj się za pomocą mediów społecznościowych');
    define('LANG_LOG_OUT',                   'Wyloguj');
    define('LANG_NO_ACCOUNT',                'Nie masz jeszcze konta?');
    define('LANG_REG_FIRST_TIME',            'Czy to Twoja pierwsza wizyta?');
    define('LANG_REG_ALREADY',               'Już zarejestrowany?');
    define('LANG_EMAIL',                     'E-mail');
    define('LANG_EMAIL_NEW',                 'Nowy adres email');
    define('LANG_EMAIL_NEW_HASH',            'Kod potwierdzający dla nowego adresu e-mail');
    define('LANG_EMAIL_NEW_HINT',            'Link potwierdzający zostanie wysłany na Twój nowy adres.');
    define('LANG_CONFIRM_CODE_ERROR',        'Wprowadzono nieprawidłowy kod weryfikacyjny');
    define('LANG_SECURITY',                  'Bezpieczeństwo');
    define('LANG_PASSWORD',                  'Hasło');
    define('LANG_RETYPE_PASSWORD',           'Powtórz hasło');
    define('LANG_USER_GROUP',                'Grupa');
    define('LANG_USER_IS_ADMIN',             'Administrator');
    define('LANG_LOGIN_ERROR',               'Nie udało się zalogować. Zweryfikuj swój adres e-mail i hasło.');
    define('LANG_LOGIN_REQUIRED',            'Zaloguj się, aby zobaczyć żądaną stronę');
    define('LANG_LOGIN_ADMIN_ONLY',          'Nie możesz się zalogować, gdy witryna jest offline');
    define('LANG_NICKNAME',                  'Przezwisko');
    define('LANG_ADMIN',                     'Administrator');
    define('LANG_EMAIL_FIND',                'Znajdź przez e-mail');
    define('LANG_FIND',                      'Znajdować');
    define('LANG_MY_PROFILE',                'Mój profil');
    define('LANG_PROFILE',                   'Profil');
    define('LANG_CITY',                      'Miasto');
    define('LANG_REGION',                    'Region');
    define('LANG_COUNTRY',                   'Kraj');
    define('LANG_COMPANY',                   'Firma');
    define('LANG_PHONE',                     'Telefon');
    define('LANG_NAME',                      'Imię');
    define('LANG_SURNAME',                   'Nazwisko');
    define('LANG_CHANGE_PASS',               'Zmień hasło');
    define('LANG_OLD_PASS',                  'Aktualne hasło');
    define('LANG_OLD_PASS_INCORRECT',        'Aktualne hasło jest nieprawidłowe');
    define('LANG_NEW_PASS',                  'Nowe hasło');
    define('LANG_RETYPE_NEW_PASS',           'Powtórz nowe hasło');
    define('LANG_PASS_CHANGED',              'Hasło poprawnie zmienione');
    define('LANG_REMEMBER_ME',               'Zapamiętaj mnie');
    define('LANG_PLEASE_LOGIN',              'Zaloguj się, proszę');
    define('LANG_LOGIN_ADMIN',               'Zaloguj się na konto administratora');
    define('LANG_ONLINE',                    'online');
    define('LANG_USERS_PROFILE_LAST_IP',     'Ostatnie IP');
    define('LANG_USERS_PROFILE_LOGDATE',     'Ostatnia wizyta');
    define('LANG_USERS_SUBSCRIBE',           'Subskrybuj');
    define('LANG_USERS_UNSUBSCRIBE',         'Anuluj subskrypcję');

    //MODERATION
    define('LANG_MODERATION',                'Umiar');
    define('LANG_MODERATION_USERS',          'Twoje materiały czekają na moderację');
    define('LANG_MODERATOR',                 'Moderator');
    define('LANG_MODERATORS',                'Moderatorzy');
    define('LANG_MODERATION_SUCCESS',        'Zatwierdzony');
    define('LANG_MODERATION_APPROVE',        'Zatwierdzić');
    define('LANG_MODERATION_RETURN',         'Usuń z moderacji');
    define('LANG_MODERATION_RETURN_FOR_REVISION', 'Powrót do przeglądu');
    define('LANG_MODERATION_REFUSE',         'Odrzuć i usuń %s');
    define('LANG_MODERATION_REFUSE_REASON',  'Jaki jest powód odrzucenia?');
    define('LANG_MODERATION_REMARKS',        'Uwagi');
    define('LANG_MODERATION_APPROVED',       'Strona została opublikowana');
    define('LANG_MODERATION_APPROVED_BY',    'Zatwierdzone przez moderatora');
    define('LANG_MODERATION_PM_AUTHOR',      'Wyślij wiadomość do autora');
    define('LANG_MODERATION_SEND',           'Zgłoś się do moderacji');
    define('LANG_MODERATION_NOTICE',         'Wpis zostanie opublikowany po zatwierdzeniu przez moderatora.');
    define('LANG_MODERATION_NOTICE_MODER',   'Wpis czeka na Twoją akceptację.');
    define('LANG_MODERATION_NOTICE_VIEW',    '%s %s już %s to %s, decyzja nie została jeszcze podjęta.');
    define('LANG_MODERATION_VIEW',           'pogląd');
    define('LANG_MODERATION_VIEWS',          'oglądane');
    define('LANG_MODERATION_IDLE',           'Powiadomienie zostało wysłane do moderatora %s');
    define('LANG_MODERATION_NO_TASKS',       'Żadne wpisy nie wymagają zatwierdzenia');
    define('LANG_MODERATION_NOTIFY',         'Nowa strona czeka na Twoją akceptację');
    define('LANG_MODERATION_RETURN_NOTIFY',  'Autor pobiera materiał z moderacji');
    define('LANG_MODERATION_REMARK_NOTIFY',  'Nagranie jest zwracane do sprawdzenia');
    define('LANG_PM_MODERATION_COMMENT_APPROVED', 'Moderator zatwierdził komentarz <b><a href="%2$s">%1$s</a></b> do publikacji%3$s');
    define('LANG_PM_MODERATION_APPROVED',    'Moderator zatwierdził publikację <b><a href="%2$s">%1$s</a></b>%3$s');
    define('LANG_PM_MODERATION_REFUSED',     'Moderator odrzucił publikację<b>%1$s</b>.%2$s Powód odrzucenia: %3$s');
    define('LANG_PM_MODERATION_COMMENT_REFUSED', 'Moderator odrzucił Twój komentarz na stronie <b>%1$s</b>.%2$s Powód odrzucenia: %3$s');
    define('LANG_PM_MODERATION_REWORK',      'Moderator zwrócił stronę <b><a href="%2$s">%1$s</a></b> do sprawdzenia i wskazał uwagi:<br />%3$s');
    define('LANG_PM_MODERATION_REWORK_DRAFT', 'Proszę poprawić uwagi w tekście.');

    //PERMISSIONS
    define('LANG_PERMISSIONS',               'Uprawnienia');
    define('LANG_PERM_RULE',                 'Reguła uprawnień');
    define('LANG_PERM_OPTION_NULL',          'NIE');
    define('LANG_PERM_OPTION_YES',           'Tak');
    define('LANG_PERM_OPTION_ALLOW',         'Umożliwić');
    define('LANG_PERM_OPTION_PREMOD',        'Z premoderacją');
    define('LANG_PERM_OPTION_PREMOD_OWN',    'Posiadaj tylko z premoderacją');
    define('LANG_PERM_OPTION_PREMOD_ALL',    'Wszystko z premoderacją');
    define('LANG_PERM_OPTION_OWN',           'Tylko własne');
    define('LANG_PERM_OPTION_OTHER',         'Tylko inni');
    define('LANG_PERM_OPTION_TO_OTHER',      'Tylko w innych');
    define('LANG_PERM_OPTION_ALL',           'Wszystko');
    define('LANG_SHOW_TO_GROUPS',            'Pokaż grupom');
    define('LANG_HIDE_FOR_GROUPS',           'Ukryj się przed grupami');
    define('LANG_PERM_OPTION_TO_OWN',        'Tylko posiadać');
    define('LANG_PERM_OPTION_TO_ALL',        'Do wszystkich');
    define('LANG_PERM_OPTION_OWN_TO_OWN',    'Posiadać na własność');
    define('LANG_PERM_OPTION_OWN_TO_OTHER',  'Własny dla innych');
    define('LANG_PERM_OPTION_OWN_TO_ALL',    'Własny dla wszystkich');
    define('LANG_PERM_OPTION_OTHER_TO_OWN',  'Inni na własność');
    define('LANG_PERM_OPTION_OTHER_TO_OTHER','Inni innym');
    define('LANG_PERM_OPTION_OTHER_TO_ALL',  'Inni wszystkim');
    define('LANG_PERM_OPTION_ALL_TO_OWN',    'Wszystko na własność');
    define('LANG_PERM_OPTION_ALL_TO_OTHER',  'Wszystko innym');
    define('LANG_PERM_OPTION_ALL_TO_ALL',    'Wszystko dla wszystkich');
    define('LANG_SHOW_TO_COUNTRIES',         'Pokaż dla krajów');
    define('LANG_HIDE_TO_COUNTRIES',         'Nie pokazuj dla krajów');
    define('LANG_ACCESS_DENIED',             'Odmowa dostępu');
    define('LANG_ACCESS_GROUP_HINT',         'Grupy, do których należysz, mają zakaz dostępu do tej strony');
    define('LANG_ACCESS_COUNTRY_HINT',       'Ta strona nie jest wyświetlana w Twoim kraju');

    //AUTHORIZATION
    define('LANG_AUTH_LOGIN',			 'Zaloguj sie');
    define('LANG_AUTH_PASSWORD',		 'Hasło');

    //PASSWORD RESTORE
    define('LANG_FORGOT_PASS',               'Zapomniałeś hasła?');

    //SYSTEM ERRORS
    define('LANG_ERROR',					 'Błąd');
    define('LANG_REQUEST_PARAMS_ERROR',		 'Błąd w parametrach: %s');
    define('LANG_FORM_ERRORS',				 'Błędy w formularzu');
    define('LANG_TRACE_STACK',				 'Ostatnie połączenia');
    define('ERR_COMPONENT_NOT_FOUND',		 'Nie znaleziono komponentu');
    define('ERR_MODEL_NOT_FOUND',			 'Nie znaleziono modelu lub nie można go odczytać');
    define('ERR_TEMPLATE_NOT_FOUND', 		 'Nie znaleziono szablonu lub nie można go odczytać');
    define('ERR_LIBRARY_NOT_FOUND', 		 'Nie znaleziono biblioteki lub nie można jej odczytać');
    define('ERR_FILE_NOT_FOUND',             'Nie znaleziono pliku');
    define('ERR_CLASS_NOT_FOUND', 		 	 'Nie znaleziono klasy lub nie można jej odczytać');
    define('ERR_CLASS_NOT_DEFINED', 		 'W pliku %s klasa <b>%s</b> nie została zdefiniowana');
    define('ERR_MODULE_NOT_FOUND', 		 	 'Nie znaleziono modułu');
    define('ERR_DATABASE_QUERY', 		 	 '<b>Błąd zapytania DB</b>: <div>%s</div>');
    define('ERR_PAGE_NOT_FOUND', 		 	 'Strona nie znaleziona');
    define('ERR_FORBIDDEN', 		 	     'Zabroniony');
    define('ERR_SITE_OFFLINE',               'Witryna jest offline');
    define('ERR_SITE_OFFLINE_FULL',          'Witryna jest offline. <a class="stretched-link text-dark" href="%s">Włącz</a>');
    define('ERR_SEARCH_TITLE',               'Szukaj');
    define('ERR_SEARCH_QUERY_INPUT',         'Co?');
    define('ERR_USER_NOT_FOUND',             'użytkownik nie istnieje');
    define('LANG_ERROR_503',                 'serwis niedostępny');
    define('LANG_ERROR_503_HINT',            'Proszę włączyć tryb debugowania w ustawieniach strony');

    //UPLOAD ERRORS
    define('LANG_UPLOAD_ERR_OK',             'Plik został pomyślnie przesłany');
    define('LANG_UPLOAD_ERR_INI_SIZE', 		 'Rozmiar pliku przekracza dozwolony limit: %s');
    define('LANG_UPLOAD_ERR_FORM_SIZE',      'Rozmiar pliku przekracza dozwolony limit');
    define('LANG_UPLOAD_ERR_PARTIAL', 		 'Plik został przesłany częściowo');
    define('LANG_UPLOAD_ERR_NO_FILE', 		 'Przesyłanie pliku nie powiodło się');
    define('LANG_UPLOAD_ERR_NO_TMP_DIR',     'Nie znaleziono folderu na pliki tymczasowe na serwerze');
    define('LANG_UPLOAD_ERR_CANT_WRITE', 'Nie udało się zapisać pliku na dysku');
    define('LANG_UPLOAD_ERR_EXTENSION', 	 'Przesyłanie pliku zostało anulowane');
    define('LANG_UPLOAD_ERR_MIME',           'Plik ma nieprawidłowy format');

    //MONEY
